- name: "Install additional helper packages"
  apt: pkg={{ item }} state=installed
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common  

- name: "Add gpg key"  
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add apt sources to list"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: 'docker-ce'

- name: "Install docker community edition"
  apt: pkg=docker-ce state=installed

- name: "Allow execution of docker command without sudo"
  user: name={{ ansible_env.SUDO_USER }}
        groups=docker
        append=yes